export { IconPicker } from './base/icon-picker/icon-picker.component'
export { Luggage } from './luggage/luggage.component'
export { NumberSlider } from './base/number-slider/number-slider.component'
export { PackingItem } from './packing-item/packing-item.component'
// export { PlacesMapComponent } from './places-map/places-map.component'
// export { PlacesFormComponent } from './places-form/places-form.component'
// export { PlacesListComponent } from './places-list/places-list.component'
export { SetsMenu } from './sets-menu/sets-menu.component'
export { TravelDestination } from './travel-destination/travel-destination.component'
